services:
  roadmk-db:
    image: postgres:16
    container_name: roadmk_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - roadmk_postgres_data:/var/lib/postgresql/data

  roadmk-api:
    build: .
    container_name: roadmk_backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - roadmk-db

  roadmk-frontend:
    build: ./roadmk-frontend
    container_name: roadmk_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - roadmk-api

volumes:
  roadmk_postgres_data: